# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

orbs:
  bundle-install: toshimaru/bundle-install@0.3.1

jobs:
  build:

    macos:
      xcode: 11.3.1 # Specify the Xcode version to use
    environment:
      BUILD_NUMBER: $CIRCLE_BUILD_NUM
      DEPLOY_DIR: ./

    steps:
      - checkout
      - bundle-install/bundle-install
      - run:
        name: install gpg
        command: brew install gpg
      - run:
        name: install 7zip
        command: brew install p7zip
      - run: bundle exec fastlane highway preset:unit_tests
