name: Unit test
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - task/*

jobs:
  validate-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: bundle install

      - name: Update RubyGems
        run: gem update --system

      - name: Run Highway
        run: bundle exec fastlane highway preset:unit_tests
        env:
          BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
